# Generated by Django 5.2.8 on 2026-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_transactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
