# Generated by Django 5.2.8 on 2026-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_transactionmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='profile/qr_codes/', verbose_name='Payment QR Code'),
        ),
    ]
